version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-node-react-website
    ports:
      - "8080:8080"
    env_file: ./server/.env
    environment:
      NODE_ENV: production
    depends_on:
      - mongo
    networks:
      - app-network
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    container_name: mongodb-database
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local
